'use strict';
const data=seasons.map((d,i)=>({...Object.fromEntries(Object.entries(d).map(([k,v])=>[k,Number.isNaN(+v)?v:+v])),i}));
const $=id=>document.getElementById(id), gold='#ffc44b',blue='#619de8';
let selected=data.length-1;
for(const id of ['season','compare']) data.forEach(d=>$(id).add(new Option(d.Season,d.i)));
$('season').value=selected;$('compare').value=6;
const fmt=(v,n=1)=>Number(v).toFixed(n),pct=v=>fmt(v*100)+'%';
function svg(id,w,h,title){$(id).innerHTML='';const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox',`0 0 ${w} ${h}`);s.setAttribute('role','group');s.setAttribute('aria-label',title);$(id).append(s);return s;}
function el(s,tag,a={},text){const n=document.createElementNS(s.namespaceURI,tag);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));if(text!==undefined)n.textContent=text;s.append(n);return n;}
function txt(s,x,y,t,a={}){return el(s,'text',{x,y,...a},t)}
function line(s,x1,y1,x2,y2,a={}){return el(s,'line',{x1,y1,x2,y2,...a})}
function interactive(n,d,description){n.setAttribute('tabindex','0');n.setAttribute('role','button');n.setAttribute('aria-label',`${d.Season}: ${description}`);el(n,'title',{},`${d.Season} · ${description} · ${d.G} games`);n.addEventListener('click',()=>choose(d.i));n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(d.i)}})}
function choose(i){selected=+i;$('season').value=i;render()}
function scatter(){const s=svg('scatter',1000,350,'Three-point volume versus accuracy by season'),x=v=>70+(v-3)/11*880,y=v=>290-(v-.2)/.3*250;
for(const v of [.2,.3,.4,.5]){line(s,70,y(v),950,y(v),{class:'gridline'});txt(s,56,y(v)+4,pct(v),{'text-anchor':'end'})}for(const v of [4,6,8,10,12,14])txt(s,x(v),313,v,{'text-anchor':'middle'});txt(s,500,342,'THREE-POINT ATTEMPTS / GAME',{'text-anchor':'middle'});txt(s,70,20,'3P ACCURACY ↑');
const shown=data.filter(d=>$('small').checked||d.G>=30||d.i===selected);
const path=shown.map(d=>`${x(d['3PA'])},${y(d['3P%'])}`).join(' ');el(s,'polyline',{points:path,fill:'none',stroke:'#619de833','stroke-width':2});
shown.slice().sort((a,b)=>(a.i===selected)-(b.i===selected)).forEach(d=>{const n=el(s,'circle',{cx:x(d['3PA']),cy:y(d['3P%']),r:Math.sqrt(d.G)*1.6,fill:d.i===selected?gold:blue,'fill-opacity':d.i===selected?1:.3,stroke:d.i===selected?gold:blue,'stroke-dasharray':d.G<30?'3 3':'none',class:'point'});interactive(n,d,`${d['3PA']} three-point attempts per game, ${pct(d['3P%'])}`);if([0,6,11,selected].includes(d.i))txt(s,x(d['3PA'])+17,y(d['3P%'])+(d.i===selected?22:-15),d.Season,{style:`fill:${d.i===selected?gold:'#c1cfdd'};font-weight:700`})});
const d=data[selected];$('shooting-note').textContent=`${d.Season}: ${d['3PA']} attempts per game at ${pct(d['3P%'])}. ${fmt(d['3PA']/d.FGA*100)}% of his field-goal attempts came from three.${d.G<30?' Small sample: '+d.G+' games.':''} The path follows seasons chronologically.${!$('small').checked&&d.G<30?' The selected season remains visible even when small samples are hidden.':''}`;}
function mix(){const s=svg('mix',550,390,'Scoring composition per game by season'),x=v=>50+v*28,y=v=>325-v*8;
for(const v of [0,10,20,30,40]){line(s,40,y(v),535,y(v),{class:'gridline'});txt(s,30,y(v)+4,v,{'text-anchor':'end'})}txt(s,40,14,'ESTIMATED POINTS / GAME');
data.forEach(d=>{let base=0;const g=el(s,'g',{class:'bar',opacity:d.i===selected?1:.58});for(const [v,c] of [[d['3P']*3,gold],[d['2P']*2,blue],[d.FT,'#869184']]){el(g,'rect',{x:x(d.i),y:y(base+v),width:19,height:v*8,fill:c});base+=v}if(d.i===selected)el(g,'rect',{x:x(d.i)-3,y:y(base)-4,width:25,height:base*8+8,fill:'none',stroke:'#fff','stroke-width':1});interactive(g,d,`${fmt(d['3P']*3)} points from threes, ${fmt(d['2P']*2)} from twos, ${fmt(d.FT)} from free throws`);if(d.i%2===0)txt(s,x(d.i)+9,345,d.Season.slice(2),{transform:`rotate(-45 ${x(d.i)+9} 345)`,'text-anchor':'end'})});}
function age(){const s=svg('age',550,390,'Scoring by age'),per36=$('basis').value==='36',val=d=>d.PTS*(per36?36/d.MP:1),x=v=>52+(v-21)/16*466,y=v=>325-v/40*280;
for(const v of [0,10,20,30,40]){line(s,52,y(v),520,y(v),{class:'gridline'});txt(s,40,y(v)+4,v,{'text-anchor':'end'})}for(const v of [21,25,29,33,37])txt(s,x(v),349,v,{'text-anchor':'middle'});txt(s,285,376,'AGE DURING SEASON',{'text-anchor':'middle'});txt(s,52,20,per36?'POINTS / 36 MINUTES':'POINTS / GAME');
el(s,'polyline',{points:data.map(d=>`${x(d.Age)},${y(val(d))}`).join(' '),fill:'none',stroke:blue,'stroke-width':3});data.forEach(d=>{const n=el(s,'circle',{cx:x(d.Age),cy:y(val(d)),r:d.i===selected?8:5,fill:d.i===selected?gold:'#131920',stroke:d.i===selected?gold:blue,'stroke-width':2,class:'point'});interactive(n,d,`${fmt(val(d))} points ${per36?'per 36 minutes':'per game'}, age ${d.Age}`)});const peak=data.reduce((a,b)=>val(a)>val(b)?a:b);txt(s,x(peak.Age),y(val(peak))-16,`${fmt(val(peak))} · age ${peak.Age}`,{'text-anchor':'middle',style:'fill:#ffc44b;font-weight:700'});$('age-note').textContent=per36?'Calculated from rounded PPG and minutes per game. This comparison adjusts for minutes, but does not measure overall impact.':'His highest scoring average: 32.0 points per game at age 32 in 2020–21. The 2019–20 dip represents only five games.';}
function compare(){const a=data[selected],b=data[+$('compare').value];$('comparison').innerHTML=`<div class="compare-row compare-head"><span>METRIC</span><span>${a.Season} · selected</span><span>${b.Season}</span></div>`;for(const [key,label,percent] of [['PTS','Points',false],['3P%','3P%',true],['eFG%','eFG%',true],['AST','Assists',false],['G','Games',false]]){const max=Math.max(...data.map(d=>d[key]));const row=document.createElement('div');row.className='compare-row';row.innerHTML=`<span>${label}</span>`+[a,b].map(d=>`<b>${percent?pct(d[key]):fmt(d[key],key==='G'?0:1)}<small style="width:${d[key]/max*100}%"></small></b>`).join('');$('comparison').append(row)}}
function render(){const d=data[selected];$('season-context').textContent=`AGE ${d.Age} · ${d.G} GAMES · REGULAR SEASON`;$('season-title').textContent=d.Season;const notes={'2009-10':'The starting point: 4.8 three-point attempts per game.','2015-16':'MVP season. 30.1 points per game with a career-best 63.0% eFG.','2020-21':'His highest scoring average, eleven years after his debut.','2019-20':'Only five games. Treat these averages as a small sample.'};$('season-note').textContent=notes[d.Season]||`${fmt(d['3PA']/d.FGA*100)}% of his field-goal attempts came from beyond the arc.`;$('stats').innerHTML=[['PTS',fmt(d.PTS),'POINTS / GAME'],['3P%',pct(d['3P%']),'THREE-POINT %'],['eFG%',pct(d['eFG%']),'EFFECTIVE FG %'],['AST',fmt(d.AST),'ASSISTS / GAME']].map(([,v,l])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('');document.querySelectorAll('[data-season]').forEach(b=>b.classList.toggle('active',b.dataset.season===d.Season));scatter();mix();age();compare()}
$('season').addEventListener('change',e=>choose(e.target.value));$('compare').addEventListener('change',compare);$('basis').addEventListener('change',age);$('small').addEventListener('change',scatter);document.querySelectorAll('[data-season]').forEach(b=>b.addEventListener('click',()=>choose(data.find(d=>d.Season===b.dataset.season).i)));render();
